version: '3.8'

services:
  birthday-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run server-node"
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped