version: '3.8'

services:
  birthday-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npx http-server -p 20000"
    ports:
      - 20000:20000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped